### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array within OeEdmModelMetadataProvider.SortClrPropertyByOrder

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#20]
Currently running into an issue in my model when using a composite primary key made up of foreign keys.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OdataToEntity.ModelBuilder.OeEdmModelMetadataProvider.SortClrPropertyByOrder(List`1 clrProperties) in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity/ModelBuilder/OeEdmModelMetadataProvider.cs:line 86
   at OdataToEntity.ModelBuilder.FKeyInfo.GetDependentStructuralProperties(OeEdmModelMetadataProvider metadataProvider, EntityTypeInfo dependentInfo, PropertyInfo dependentProperty) in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity/ModelBuilder/FKeyInfo.cs:line 85
   at OdataToEntity.ModelBuilder.FKeyInfo.Create(OeEdmModelMetadataProvider metadataProvider, Dictionary`2 entityTypes, EntityTypeInfo dependentInfo, PropertyInfo dependentNavigationProperty) in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity/ModelBuilder/FKeyInfo.cs:line 49
   at OdataToEntity.ModelBuilder.EntityTypeInfo.BuildProperty(Dictionary`2 entityTypes, Dictionary`2 enumTypes, Dictionary`2 complexTypes, PropertyInfo clrProperty) in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity/ModelBuilder/EntityTypeInfo.cs:line 102
   at OdataToEntity.ModelBuilder.EntityTypeInfo.BuildProperties(Dictionary`2 entityTypes, Dictionary`2 enumTypes, Dictionary`2 complexTypes) in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity/ModelBuilder/EntityTypeInfo.cs:line 128
   at OdataToEntity.ModelBuilder.OeEdmModelBuilder.BuildEdmModel() in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity/ModelBuilder/OeEdmModelBuilder.cs:line 70
   at OdataToEntity.EfCore.OeEfCoreDataAdapterExtension.BuildEdmModelFromEfCoreModel(OeDataAdapter dataAdapter) in /Users/techniq/Documents/Development/open-source/OdataToEntity/source/OdataToEntity.EfCore/OeEfCoreDataAdapterExtension.cs:line 18
   at OdataToEntityTest.Startup.ConfigureServices(IServiceCollection services) in /Users/techniq/Documents/Development/playground/odata-to-entity/OdataToEntityTest/Startup.cs:line 40
```

Here is a model that demonstrates the issue (not my actual model, just a contrived example)
```c#
public class MyCommonDbContext : DbContext
    {
        public DbSet<Car> Cars { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<LicensePlate> LicensePlates { get; set; }

        public MyCommonDbContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Car>().HasKey(c => new { c.StateId, c.LicensePlateId });
        }
    }

    public class Car
    {
        public int StateId { get; set; }
        public int LicensePlateId { get; set; }

        public string Make { get; set; }
        public string Model { get; set; }

        public virtual State State { get; set; }
        public virtual LicensePlate LicensePlate { get; set; }
    }

    public class State
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Car> Cars { get; set; }
    }

    public class LicensePlate
    {
        public int Id { get; set; }
        public string Text { get; set; }

        public virtual ICollection<Car> Cars { get; set; }
    }
```

In [OeEdmModelMetadataProvider.SortClrPropertyByOrder](https://github.com/voronov-maxim/OdataToEntity/blob/master/source/OdataToEntity/ModelBuilder/OeEdmModelMetadataProvider.cs#L68) it builds a `propertyList` based on the size of the passed in `clrProperties`, but the value returned from [OeEfCoreEdmModelMetadataProvider.GetOrder](https://github.com/voronov-maxim/OdataToEntity/blob/master/source/OdataToEntity.EfCore/OeEfCoreEdmModelMetadataProvider.cs#L75) is bigger
```c#
public PropertyInfo[] SortClrPropertyByOrder(List<PropertyInfo> clrProperties)
{
    var propertyList = new PropertyInfo[clrProperties.Count];
    foreach (PropertyInfo clrProperty in clrProperties)
    {
        int order = GetOrder(clrProperty);
        if (order == -1)
        {
            clrProperties.CopyTo(propertyList);
            break;
        }
        propertyList[order] = clrProperty;
    }

    return propertyList;
}
```

**Comment by voronov-maxim** [comment]
@techniq Many thanks

**Comment by techniq** [comment]
@voronov-maxim Thanks for the quick turnaround.  I need to update to dotnet 2.1 and then pull your changes and I'll let you know if I run into anything else (only about 20% through all my models)

**Comment by techniq** [comment]
@voronov-maxim works great.  I'm still running into some null issues (see: #16) and need to finish upgrading fully to dotnet 2.1 to test further, but so far this looks fixed.  Thanks again.
